name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Bước dvc
  dvc_repro:
    runs-on: ubuntu-latest  # Sử dụng Ubuntu môi trường
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install DVC and AWS CLI
        run: |
          pip install dvc[all]
          pip install awscli  # Cài đặt AWS CLI bằng pip

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-southeast-2  # Thiết lập khu vực nếu cần

      - name: Check AWS S3 access
        run: aws s3 ls  # Kiểm tra quyền truy cập S3

      - name: Pull data from remote storage
        run: dvc pull  # Tải dữ liệu từ remote storage

      - name: Reproduce DVC pipeline
        run: dvc repro  # Train lại mô hình

      - name: Push results to remote storage
        run: dvc push  # Đẩy kết quả mới lên remote storage

    outputs:
      models: models/
      data: data/

  # Bước kiểm thử
  test:
    runs-on: ubuntu-latest
    needs: dvc_repro  # Đảm bảo dvc_repro chạy trước

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt  # Cài đặt các phụ thuộc

      - name: Run tests
        run: pytest tests/  # Chạy tất cả các unit test trong thư mục tests

      - name: Upload test reports as artifacts
        uses: actions/upload-artifact@v3  # Cập nhật lên phiên bản mới nhất v3
        with:
          name: test-reports
          path: tests/reports  # Đảm bảo thư mục này tồn tại trong quá trình chạy

  # Bước Docker
  build_docker:
    runs-on: ubuntu-latest
    needs: [dvc_repro, test]  # Chạy sau khi dvc_repro và test hoàn tất

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$GITHUB_SHA .

      - name: Push Docker image
        run: |
          docker push $CI_REGISTRY/$CI_PROJECT_PATH:$GITHUB_SHA
