name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  dvc_repro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.7'
      - name: Install dependencies
        run: |
          pip install dvc[all]
          pip install awscli  # Cài đặt AWS CLI bằng pip
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}  # Nếu cần, bạn có thể thêm khu vực AWS
      - name: Check S3 access
        run: aws s3 ls
      - name: Pull data with DVC
        run: dvc pull
      - name: Reproduce DVC pipeline
        run: dvc repro
      - name: Push results to DVC remote storage
        run: dvc push
      - name: Upload models as artifact
        uses: actions/upload-artifact@v3
        with:
          name: models
          path: models/
      - name: Upload data as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: data
          path: data/

  test:
    runs-on: ubuntu-latest  # Use Ubuntu for testing
    needs: dvc_repro  # Only run after dvc_repro job is complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.7'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: tests/reports/

  build_docker:
    runs-on: ubuntu-latest  # Use Ubuntu for Docker setup
    needs: test  # Only run after test job is complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets for Docker credentials
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }} .
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
