name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dvc_repro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install DVC and AWS CLI
        run: |
          pip install dvc[all]
          pip install awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-southeast-2

      - name: Check AWS S3 access
        run: aws s3 ls

      - name: Pull data from remote storage
        run: dvc pull

      - name: Reproduce DVC pipeline
        run: dvc repro

      - name: Push results to remote storage
        run: dvc push

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: house-price-model
          path: models/house_price_model.pkl


  # Bước kiểm thử
  test:
    runs-on: ubuntu-latest
    needs: dvc_repro

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: house-price-model
          path: models/

      - name: Verify model file
        run: |
          ls models/
          if [ ! -f models/house_price_model.pkl ]; then
            echo "Model file not found!";
            exit 1;
          fi

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Upload test reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: tests/reports


  # Bước Docker
  build_docker:
    runs-on: ubuntu-latest
    needs: [dvc_repro, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myproject:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myproject:${{ github.sha }}